<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="link authorization-link login-authorization" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
    <?php if ($block->isLoggedIn()): ?>
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>
        <?= /* @noEscape */ $dataPostParam ?>>Custom <?= $escaper->escapeHtml($block->getLabel()) ?></a>
    <?php else: ?>
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?>
            <?= /* @noEscape */ $dataPostParam ?>><?= $escaper->escapeHtml($block->getLabel()) ?></a>
        <script>
            require([
                'jquery',
                'Magento_Customer/js/model/authentication-popup',
                'Magento_Customer/js/customer-data'
                ], function($, authenticationPopup, customerData){
                $(document).ready(function()){
                    $('.login-authorization > a').on('click', function(event) {

                        var customer = customerData.get('customer');

                        event.preventDefault();

                        if(!customer().firstname) {
                            authenticationPopup.showModal();
                            return false;
                        }

                        return true;
                    });
                });
            });
        </script>
    <?php endif; ?>
</li>
